name: ko-post
run-name: ko-post
on: [push] 
jobs:
  posting-new-ko-entry:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6
       with:
        repository: 'Cappucciyes/blog'
        ref: 'main'
        token:  ${{ secrets.BLOG_TOKEN }}

     - name: Setup git config
       run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"
      
 
  